# Generated by Django 5.2.3 on 2026-07-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availble',
            new_name='is_available',
        ),
    ]
